### ISSUE TITLE
AttributeError: 'TypeProto' object has no attribute 'sequence_type'

### ISSUE THREAD

**Issue by dimidd** [onnx/onnxmltools#135]
Hi,

I tried to play with the example from the tests:
```
import onnxmltools
from sklearn.datasets import load_iris
from sklearn.svm import SVC, SVR, NuSVC, NuSVR
from onnxmltools import convert_sklearn
from onnxmltools.convert.common.data_types import FloatTensorType
 
iris = load_iris()
X = iris.data[:, :3]
y = iris.target
model = SVC(kernel='linear', probability=False)
model.fit(X, y)
nodes = convert_sklearn(model, 'SVC', [('input', FloatTensorType([1, 1]))]).graph.node
```
And got the error in the title. Am I missing something?

Versions:
onnx                     1.3.0
onnxmltools              1.2.2.129
scikit-learn             0.19.2

**Comment by wschin** [comment]
Please try to set up an environment variable, `ONNX_ML=1`, and reinstall onnx python package. There are two versions of ONNX format. The default one doesn't contain enough types to support machine learning pipelines.

**Comment by bball3212** [comment]
I have this same issue, and the solution didnt work...anyone else?

**Comment by enpinzolas** [comment]
I have the same issue, I set the environment variable before reinstalling and I tried reinstalling both from source and pip to no avail.

I have also tried reinstalling onnxmltools both from pip and source, after setting up the environment variable.

**Comment by wschin** [comment]
What's your OS? Could you provide more details like printing out your environment variables?

**Comment by enpinzolas** [comment]
Sure. I'm on linux, a Ubuntu 16.04 machine. These are the environment variables:
```
XDG_SESSION_ID=216
TERM=xterm
SHELL=/bin/bash
SSH_CLIENT=XXXXXXXX
CONDA_SHLVL=2
CONDA_PROMPT_MODIFIER=(onnx)
OLDPWD=/home/XXX
SSH_TTY=/dev/pts/1
http_proxy=XXXXXXXXXXXXXXXXX
USER=XXX
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
ONNX_ML=1
CONDA_EXE=/home/XXX/.miniconda/bin/conda
CONDA_PREFIX_1=/home/XXX/.miniconda
MAIL=/var/mail/XXX
PATH=/home/XXX/.miniconda/envs/onnx/bin:/home/XXX/bin:/home/XXX/.local/bin:/home/XXX/.miniconda/bin:/home/XXX/.miniconda/condabin:/home/XXX/.miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
CONDA_PREFIX=/home/XXX/.miniconda/envs/onnx
PWD=/var/opt/MLFramework Test/onnx
LANG=es_ES.UTF-8
https_proxy=XXXXXXXXXXXXXX
SHLVL=1
HOME=/home/XXX
CONDA_PYTHON_EXE=/home/XXX/.miniconda/bin/python
LOGNAME=XXX
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
SSH_CONNECTION=XXXXXXXXXXXXXXXXXXXX
CONDA_DEFAULT_ENV=onnx
LESSOPEN=| /usr/bin/lesspipe %s
XDG_RUNTIME_DIR=/run/user/1000
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/printenv
```

And this is the execution output.

```bash
(onnx) XXX@ubuntu:/var/opt/MLFramework Test/onnx$ echo $ONNX_ML
1
```
```bash
(onnx) XXX@ubuntu:/var/opt/MLFramework Test/onnx$ pip install -I onnx
Collecting onnx
Collecting six (from onnx)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting typing>=3.6.4 (from onnx)
  Using cached https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
Collecting protobuf (from onnx)
  Using cached https://files.pythonhosted.org/packages/3a/30/289ead101f94998d88e8961a3548aea29417ae0057be23972483cddebf4f/protobuf-3.6.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting numpy (from onnx)
  Using cached https://files.pythonhosted.org/packages/61/57/07c49e1a6d2706fb7336b3fb11dd285c1e96535c80833d7524f002f57086/numpy-1.16.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting typing-extensions>=3.6.2.1 (from onnx)
  Using cached https://files.pythonhosted.org/packages/0f/62/c66e553258c37c33f9939abb2dd8d2481803d860ff68e635466f12aa7efa/typing_extensions-3.7.2-py3-none-any.whl
Collecting setuptools (from protobuf->onnx)
  Using cached https://files.pythonhosted.org/packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl
Installing collected packages: six, typing, setuptools, protobuf, numpy, typing-extensions, onnx
Successfully installed numpy-1.16.1 onnx-1.4.1 protobuf-3.6.1 setuptools-40.8.0 six-1.12.0 typing-3.6.6 typing-extensions-3.7.2
```
```bash
(onnx) XXX@ubuntu:/var/opt/MLFramework Test/onnx$ pip install -I onnxmltools
Collecting onnxmltools
  Using cached https://files.pythonhosted.org/packages/9a/e6/083b6fe47400f49f02e1909b8327c955e0a3a2f64477bb524528a73960f6/onnxmltools-1.3.1-py2.py3-none-any.whl
Collecting six (from onnxmltools)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting numpy (from onnxmltools)
  Using cached https://files.pythonhosted.org/packages/61/57/07c49e1a6d2706fb7336b3fb11dd285c1e96535c80833d7524f002f57086/numpy-1.16.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting protobuf (from onnxmltools)
  Using cached https://files.pythonhosted.org/packages/3a/30/289ead101f94998d88e8961a3548aea29417ae0057be23972483cddebf4f/protobuf-3.6.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting onnx (from onnxmltools)
Collecting setuptools (from protobuf->onnxmltools)
  Using cached https://files.pythonhosted.org/packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl
Collecting typing>=3.6.4 (from onnx->onnxmltools)
  Using cached https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
Collecting typing-extensions>=3.6.2.1 (from onnx->onnxmltools)
  Using cached https://files.pythonhosted.org/packages/0f/62/c66e553258c37c33f9939abb2dd8d2481803d860ff68e635466f12aa7efa/typing_extensions-3.7.2-py3-none-any.whl
Installing collected packages: six, numpy, setuptools, protobuf, typing, typing-extensions, onnx, onnxmltools
Successfully installed numpy-1.16.1 onnx-1.4.1 onnxmltools-1.3.1 protobuf-3.6.1 setuptools-40.8.0 six-1.12.0 typing-3.6.6 typing-extensions-3.7.2
```
```bash
(onnx) XXX@ubuntu:/var/opt/MLFramework Test/onnx$ python onnx-tutorial.py
/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)
Traceback (most recent call last):
  File "onnx-tutorial.py", line 17, in <module>
    onx = convert_sklearn(clr, initial_types=initial_type)
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/main.py", line 50, in convert_sklearn
    custom_conversion_functions, custom_shape_calculators)
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/sklearn/convert.py", line 93, in convert
    topology.compile()
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/common/_topology.py", line 625, in compile
    self._infer_all_types()
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/common/_topology.py", line 501, in _infer_all_types
    operator.infer_types()
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/common/_topology.py", line 103, in infer_types
    _registration.get_shape_calculator(self.type)(self)
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/common/shape_calculator.py", line 28, in calculate_linear_classifier_output_shapes
    check_input_and_output_types(operator, good_input_types=[FloatTensorType, Int64TensorType])
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/common/utils.py", line 290, in check_input_and_output_types
    good_input_types))
RuntimeError: Operator SklearnLinearClassifier (type: SklearnLinearClassifier) got an input float_input with a wrong type <class 'skl2onnx.common.data_types.FloatTensorType'>. Only [<class 'onnxmltools.convert.common.data_types.FloatTensorType'>, <class 'onnxmltools.convert.common.data_types.Int64TensorType'>] are allowed
(onnx) XXX@ubuntu:/var/opt/MLFramework Test/onnx$ python onnx-tutorial.py
/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)
Traceback (most recent call last):
  File "onnx-tutorial.py", line 17, in <module>
    onx = convert_sklearn(clr, initial_types=initial_type)
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/main.py", line 50, in convert_sklearn
    custom_conversion_functions, custom_shape_calculators)
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/sklearn/convert.py", line 96, in convert
    onnx_model = convert_topology(topology, name, doc_string, target_opset, targeted_onnx)
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/common/_topology.py", line 712, in convert_topology
    container.add_output(other_outputs[name])
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/common/_container.py", line 165, in add_output
    self.outputs.append(self._make_value_info(variable))
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/common/_container.py", line 146, in _make_value_info
    value_info.type.CopyFrom(variable.type.to_onnx_type())
  File "/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages/onnxmltools/convert/common/data_types.py", line 135, in to_onnx_type
    onnx_type.sequence_type.elem_type.CopyFrom(self.element_type.to_onnx_type())
AttributeError: 'TypeProto' object has no attribute 'sequence_type'

```

There are some warnings but I don't think that they are about the error.

Lastly, this is the code that I'm trying to execute:

```python
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from onnxmltools import convert_sklearn
from onnxmltools.convert.common.data_types import FloatTensorType

iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y)

clr = LogisticRegression()
clr.fit(X_train, y_train)
print(clr)


initial_type = [('float_input', FloatTensorType([1, 4]))]
onx = convert_sklearn(clr, initial_types=initial_type)
with open("logreg_iris.onnx", "wb") as f:
    f.write(onx.SerializeToString())
```

I must be doing something wrong but I am not seeing it!

**Comment by wschin** [comment]
Looks like you're using anaconda, so there could be multiple different python environments. Are you sure that `pip` and `python` are associated to the same environment? Could you print out the package installation paths and the module paths imported in your script?

**Comment by enpinzolas** [comment]
Thank you for your time.

Both pip and conda are indeed associated to the same environment:

```
(onnx) XXX@ubuntu:/var/opt/MLFramework Test/onnx$ which python
/home/XXX/.miniconda/envs/onnx/bin/python
(onnx) XXX@ubuntu:/var/opt/MLFramework Test/onnx$ which pip
/home/XXX/.miniconda/envs/onnx/bin/pip
(onnx) XXX@ubuntu:/var/opt/MLFramework Test/onnx$ python -c "import site; print(site.getsitepackages())"
['/home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages']
```
Inside the packages site are these packages (I'm excludiong those that are not the ones I used in the script besides the ones related to onnx):

```
(onnx) XXX@ubuntu:/var/opt/MLFramework Test/onnx$ ls /home/XXX/.miniconda/envs/onnx/lib/python3.7/site-packages -lha
{...}
drwxrwxr-x  14 XXX XXX 4,0K feb 21 09:39 onnx
drwxrwxr-x   2 XXX XXX 4,0K feb 21 09:39 onnx-1.4.1.dist-info
drwxrwxr-x   6 XXX XXX 4,0K feb 21 09:39 onnxmltools
drwxrwxr-x   2 XXX XXX 4,0K feb 21 09:39 onnxmltools-1.3.1.dist-info
drwxrwxr-x   7 XXX XXX 4,0K feb 20 09:27 onnxruntime
drwxrwxr-x   2 XXX XXX 4,0K feb 20 09:27 onnxruntime-0.2.1.dist-info
drwxrwxr-x   3 XXX XXX 4,0K feb 20 12:16 onnxtk
drwxrwxr-x   2 XXX XXX 4,0K feb 20 12:16 onnxtk-0.0.1.dist-info
{...}
drwxrwxr-x   2 XXX XXX 4,0K feb 20 09:28 scikit_learn-0.20.2.dist-info
drwxrwxr-x   7 XXX XXX 4,0K feb 20 12:16 scikitonx
drwxrwxr-x  22 XXX XXX 4,0K feb 20 12:16 scipy
drwxrwxr-x   2 XXX XXX 4,0K feb 20 12:16 scipy-1.2.1.dist-info
{...}
drwxrwxr-x   7 XXX XXX 4,0K feb 20 12:16 skl2onnx
drwxrwxr-x   2 XXX XXX 4,0K feb 20 12:16 skl2onnx-1.4.2.dist-info
drwxrwxr-x  29 XXX XXX 4,0K feb 20 09:28 sklearn
{...}
drwxrwxr-x   6 XXX XXX 4,0K feb 20 12:17 tf2onnx
drwxrwxr-x   2 XXX XXX 4,0K feb 20 12:17 tf2onnx-0.3.2.dist-info
{...}
```

By the way, if I install though pip I need to use `onnxmltools.convert.common.data_types` while if I  install throush source it requires `skl2onnx.common.data_types`. Is this normal? Which version is the more robust one?

**Comment by wenbingl** [comment]
The latest ONNX package already has ONNX_ML==1 set by default, please have a try.
There are some recent changes that sklearn converter has separated from onnxmltools so the answer is skl2onnx.common.data_types.

**Comment by enpinzolas** [comment]
In the end, I was trying to test other ways to deploy models, and I installed onnx from anaconda by chance. With this onnx version, the script executed correctly.

It´s a pitty that I'm not 100% sure if it was the onnx version or another thing, but I got it to work by installing onnx through:
```bash 
 conda install -y -c conda-forge onnx
```
