### ISSUE TITLE
Lambda layer in Keras not implemented?

### ISSUE THREAD

**Issue by anuar12** [onnx/onnxmltools#159]
Hey, thank you for a great library!

I was trying to convert Yolov2 object detection model from Keras->ONNX and got this error:
`Traceback (most recent call last):
  File "predict.py", line 179, in <module>
    _main_(args)
  File "predict.py", line 84, in _main_
    onnx_model = onnxmltools.convert_keras(yolo.model)
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/main.py", line 38, in convert_keras
    target_opset, targeted_onnx, custom_conversion_functions, custom_shape_calculators)
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/keras/convert.py", line 43, in convert
    topology.compile()
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/common/_topology.py", line 624, in compile
    self._infer_all_types()
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/common/_topology.py", line 500, in _infer_all_types
    operator.infer_types()
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/common/_topology.py", line 101, in infer_types
    _registration.get_shape_calculator(self.type)(self)
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/common/_registration.py", line 68, in get_shape_calculator
    raise ValueError('Unsupported shape calculation for operator %s' % operator_name)
ValueError: Unsupported shape calculation for operator <class 'keras.layers.core.Lambda'>`

Is Lambda layer implemented?

Thank you!

**Comment by anuar12** [comment]
So I got rid of the Lambda layer but then got the next error with identity operator. Not sure what to do next since as far as I know there isn't identity layer in keras and don't see where I create identity in my network...

Here's trace:
`
Traceback (most recent call last):
  File "predict.py", line 179, in <module>
    _main_(args)
  File "predict.py", line 85, in _main_
    onnx_model = onnxmltools.convert_keras(yolo_inf)
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/main.py", line 38, in convert_keras
    target_opset, targeted_onnx, custom_conversion_functions, custom_shape_calculators)
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/keras/convert.py", line 43, in convert
    topology.compile()
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/common/_topology.py", line 624, in compile
    self._infer_all_types()
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/common/_topology.py", line 500, in _infer_all_types
    operator.infer_types()
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/common/_topology.py", line 101, in infer_types
    _registration.get_shape_calculator(self.type)(self)
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/common/_registration.py", line 68, in get_shape_calculator
    raise ValueError('Unsupported shape calculation for operator %s' % operator_name)
ValueError: Unsupported shape calculation for operator identity
`

**Comment by wenbingl** [comment]
which yolo v2 model are you trying? I can take a look to see the what's the issue.

**Comment by anuar12** [comment]
I uploaded an .h5 if you want to try import it yourself: https://drive.google.com/file/d/1gO_9ZedHcpxu-Syn9c22bCcNR8lnfhhG/view?usp=sharing 

If you want to look at the code it's from this repo (mostly backend.py and frontend.py of FullYolo model). https://github.com/experiencor/keras-yolo2

**Comment by wenbingl** [comment]
Yes, the existing keras converter has design limitation to support Lambda and customize layer, probably there will be a new one which can do it. Before that, you can convert the model to TF format and use tenflow-onnx to have a workaround for that.
