### ISSUE TITLE
Error when converting cnn-emotion-detection from CoreML

### ISSUE THREAD

**Issue by lupesko** [onnx/onnxmltools#20]
Trying to convert a CNN emotion detection coreml model I get an error.

Model: https://coreml.store/cnnemotions
Config: Python 3.6.4, OSX
Install: from source using `pip install git+https://github.com/onnx/onnxmltools`
Script and error:
```
>>> import onnxmltools
>>> import coremltools
>>> model_coreml = coremltools.utils.load_spec('CNNEmotions.mlmodel')
>>> model_onnx = onnxmltools.convert_coreml(model_coreml, 'Image_Reco')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hag/anaconda/envs/mms-onnx-talk-3-6/lib/python3.6/site-packages/onnxmltools/convert/main.py", line 23, in convert_coreml
    return convert(model, name)
  File "/Users/hag/anaconda/envs/mms-onnx-talk-3-6/lib/python3.6/site-packages/onnxmltools/convert/coreml/convert.py", line 77, in convert
    nodes = _convert_coreml_node(context, spec)
  File "/Users/hag/anaconda/envs/mms-onnx-talk-3-6/lib/python3.6/site-packages/onnxmltools/convert/coreml/convert.py", line 310, in _convert_coreml_node
    return _convert_neural_network(context, cm_node)
  File "/Users/hag/anaconda/envs/mms-onnx-talk-3-6/lib/python3.6/site-packages/onnxmltools/convert/coreml/convert.py", line 267, in _convert_neural_network
    context, converter, nn_layer, inputs, outputs)
  File "/Users/hag/anaconda/envs/mms-onnx-talk-3-6/lib/python3.6/site-packages/onnxmltools/convert/coreml/convert.py", line 115, in _do_convert
    nodes = converter.convert(context, cm_node, input, output)
  File "/Users/hag/anaconda/envs/mms-onnx-talk-3-6/lib/python3.6/site-packages/onnxmltools/convert/coreml/NeuralNetwork/pooling.py", line 154, in convert
    raise ValueError('Unsupported padding mode: {}'.format(pad_type))
ValueError: Unsupported padding mode: includeLastPixel
```

**Comment by FrozenGene** [comment]
The latest source should not have problem, I have used the latest source code , can not reproduce.

**Comment by wschin** [comment]
As @FrozenGene said, includeLastPixel padding is supported now.

**Comment by glennparham** [comment]
I'm having this same issue and I followed OP's steps...Any ideas?

**Comment by wschin** [comment]
Please install onnxmltools from its source: `pip install git+https://github.com/onnx/onnxmltools`
