### ISSUE TITLE
An error (Elu function) occured while loading model with winmltools which uses onnxmltools.

### ISSUE THREAD

**Issue by faruknane** [onnx/onnxmltools#214]
Hi, I use elu function in my model and I want to convert the model (from keras tensorflow) to ONNX format in order to use it with C# windows app. 

I try to load the model with winmltools using the code below:
```
from winmltools import convert_keras
model_onnx = convert_keras(model, target_opset=8, name="cropper")
```

It gave me an error:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-8-156ad53f924e> in <module>()
      1 from winmltools import convert_keras
      2 
----> 3 model_onnx = convert_keras(model, target_opset=8, name="cropper")
      4 print(type(model_onnx))
      5 if False:

/usr/local/lib/python3.6/dist-packages/winmltools/convert/main.py in convert_keras(model, target_opset, name, initial_types, doc_string, default_batch_size, channel_first_inputs, custom_conversion_functions, custom_shape_calculators)
    151     return _convert_keras(model, name=name, target_opset=target_opset, initial_types=initial_types, doc_string=doc_string,
    152                           default_batch_size=default_batch_size, channel_first_inputs=channel_first_inputs,
--> 153                           custom_conversion_functions=custom_conversion_functions, custom_shape_calculators=custom_shape_calculators)
    154 
    155 

/usr/local/lib/python3.6/dist-packages/onnxmltools/convert/keras/convert.py in convert(model, name, default_batch_size, initial_types, doc_string, target_opset, targeted_onnx, channel_first_inputs, custom_conversion_functions, custom_shape_calculators)
     46         name = str(uuid4().hex)
     47 
---> 48     onnx_model = convert_topology(topology, name, doc_string, target_opset, targeted_onnx, channel_first_inputs)
     49     return onnx_model

/usr/local/lib/python3.6/dist-packages/onnxmltools/convert/common/_topology.py in convert_topology(topology, model_name, doc_string, target_opset, targeted_onnx, channel_first_inputs)
    719         else:
    720             # Convert the selected operator into some ONNX objects and save them into the container
--> 721             _registration.get_converter(operator.type)(scope, operator, container)
    722 
    723     # When calling ModelComponentContainer's add_initializer(...), nothing is added into the input list. However, in

/usr/local/lib/python3.6/dist-packages/onnxmltools/convert/keras/operator_converters/Conv.py in convert_keras_conv2d(scope, operator, container)
    144 def convert_keras_conv2d(scope, operator, container):
    145     is_transpose, n_dims, input_perm, output_perm, weight_perm = get_converter_config(2, False)
--> 146     convert_keras_conv_core(scope, operator, container, is_transpose, n_dims, input_perm, output_perm, weight_perm)
    147 
    148 

/usr/local/lib/python3.6/dist-packages/onnxmltools/convert/keras/operator_converters/Conv.py in convert_keras_conv_core(scope, operator, container, is_transpose, n_dims, input_perm_axes, output_perm_axes, weight_perm_axes)
    117     # The construction of convolution is done. Now, we create an activation operator to apply the activation specified
    118     # in this Keras layer.
--> 119     apply_activation_function = _activation_map[op.activation]
    120     activation_output_name = scope.get_unique_variable_name('activation_output')
    121     apply_activation_function(scope, intermediate_output_name, activation_output_name, container)

KeyError: <function elu at 0x7f48da1697b8>
```
I did some research and found out that ONNX format supports ELU function. Is there anything that I do wrong or is it a bug?

**Comment by wenbingl** [comment]
Yes, it does support 'elu'. Can you share the model or a  demo to help us identify the issue.

**Comment by faruknane** [comment]
@wenbingl  Could you inform me about what is going on please?

**Comment by wenbingl** [comment]
The fixing has been merged into github, can you update your onnxmltools and try it again.

**Comment by faruknane** [comment]
Now, I can't install it. It gives error like this. I'm working on google colab. I was able to install onnxmltools correctly. However now it gives an error. Could you help me with that @wenbingl ?
`pip install onnxmltools`
```
Collecting onnxmltools
  Downloading https://files.pythonhosted.org/packages/9a/e6/083b6fe47400f49f02e1909b8327c955e0a3a2f64477bb524528a73960f6/onnxmltools-1.3.1-py2.py3-none-any.whl (278kB)
    100% |████████████████████████████████| 286kB 16.1MB/s 
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from onnxmltools) (1.11.0)
Collecting onnx (from onnxmltools)
  Downloading https://files.pythonhosted.org/packages/59/09/61f817a530cd9b9bd0e289bc9cda46f662fcda4dc1bd687b36d45365e3ea/onnx-1.4.1.tar.gz (2.9MB)
    100% |████████████████████████████████| 2.9MB 13.5MB/s 
Requirement already satisfied: protobuf in /usr/local/lib/python3.6/dist-packages (from onnxmltools) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from onnxmltools) (1.14.6)
Collecting typing>=3.6.4 (from onnx->onnxmltools)
  Downloading https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
Collecting typing-extensions>=3.6.2.1 (from onnx->onnxmltools)
  Downloading https://files.pythonhosted.org/packages/0f/62/c66e553258c37c33f9939abb2dd8d2481803d860ff68e635466f12aa7efa/typing_extensions-3.7.2-py3-none-any.whl
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf->onnxmltools) (40.6.3)
Building wheels for collected packages: onnx
  Running setup.py bdist_wheel for onnx ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-795csx0y/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-zs9by7j4 --python-tag cp36:
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  -- Build type not set - defaulting to Release
  -- The C compiler identification is GNU 7.3.0
  -- The CXX compiler identification is GNU 7.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  CMake Error at /usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
    Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)
  Call Stack (most recent call first):
    /usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
    /usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindProtobuf.cmake:543 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    CMakeLists.txt:104 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-795csx0y/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-795csx0y/onnx/.setuptools-cmake-build/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-795csx0y/onnx/setup.py", line 328, in <module>
      'backend-test-tools = onnx.backend.test.cmd_tools:main',
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/dist-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-795csx0y/onnx/setup.py", line 203, in run
      self.run_command('cmake_build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-795csx0y/onnx/setup.py", line 190, in run
      subprocess.check_call(cmake_args)
    File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-x86_64-linux-gnu.so', '/tmp/pip-install-795csx0y/onnx']' returned non-zero exit status 1.
  
  ----------------------------------------
  Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
Installing collected packages: typing, typing-extensions, onnx, onnxmltools
  Running setup.py install for onnx ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-795csx0y/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-uz7pi6v5/install-record.txt --single-version-externally-managed --compile:
    fatal: not a git repository (or any of the parent directories): .git
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    CMake Error at /usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
      Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)
    Call Stack (most recent call first):
      /usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
      /usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindProtobuf.cmake:543 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      CMakeLists.txt:104 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-795csx0y/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-795csx0y/onnx/.setuptools-cmake-build/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-795csx0y/onnx/setup.py", line 328, in <module>
        'backend-test-tools = onnx.backend.test.cmd_tools:main',
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-795csx0y/onnx/setup.py", line 203, in run
        self.run_command('cmake_build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-795csx0y/onnx/setup.py", line 190, in run
        subprocess.check_call(cmake_args)
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-x86_64-linux-gnu.so', '/tmp/pip-install-795csx0y/onnx']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-795csx0y/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-uz7pi6v5/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-795csx0y/onnx/
```

**Comment by wenbingl** [comment]
This is a bug in the latest onnx pakcage,  please try to 'pip install onnx==1.3.0'.

**Comment by faruknane** [comment]
@wenbingl  the same error happened for 1.3.0 :(

**Comment by faruknane** [comment]
@wenbingl I wrote unconciously 'pip install onnxmltools==1.3.0' insted of 'pip install onnx==1.3.0'. It's 4.00 am here :/
I installed it but still gives the same error.

```
!pip install onnx==1.3.0
!pip install onnxmltools
```

```
Requirement already satisfied: onnx==1.3.0 in /usr/local/lib/python3.6/dist-packages (1.3.0)
Requirement already satisfied: typing>=3.6.4 in /usr/local/lib/python3.6/dist-packages (from onnx==1.3.0) (3.6.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from onnx==1.3.0) (1.14.6)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.6/dist-packages (from onnx==1.3.0) (3.7.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.6/dist-packages (from onnx==1.3.0) (3.6.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from onnx==1.3.0) (1.11.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf->onnx==1.3.0) (40.6.3)
Collecting onnxmltools
  Downloading https://files.pythonhosted.org/packages/9a/e6/083b6fe47400f49f02e1909b8327c955e0a3a2f64477bb524528a73960f6/onnxmltools-1.3.1-py2.py3-none-any.whl (278kB)
    100% |████████████████████████████████| 286kB 16.2MB/s 
Requirement already satisfied: protobuf in /usr/local/lib/python3.6/dist-packages (from onnxmltools) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from onnxmltools) (1.14.6)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from onnxmltools) (1.11.0)
Requirement already satisfied: onnx in /usr/local/lib/python3.6/dist-packages (from onnxmltools) (1.3.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf->onnxmltools) (40.6.3)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.6/dist-packages (from onnx->onnxmltools) (3.7.2)
Requirement already satisfied: typing>=3.6.4 in /usr/local/lib/python3.6/dist-packages (from onnx->onnxmltools) (3.6.6)
Installing collected packages: onnxmltools
Successfully installed onnxmltools-1.3.1
```

```
from onnxmltools import convert_keras
model_onnx = convert_keras(model, target_opset=7, name="cropper")
```

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-8-178d35d3091b> in <module>()
      1 from onnxmltools import convert_keras
----> 2 model_onnx = convert_keras(model, target_opset=7, name="cropper")
      3 

/usr/local/lib/python3.6/dist-packages/onnxmltools/convert/main.py in convert_keras(model, name, initial_types, doc_string, target_opset, targeted_onnx, channel_first_inputs, custom_conversion_functions, custom_shape_calculators, default_batch_size)
     28     from .keras.convert import convert
     29     return convert(model, name, default_batch_size, initial_types, doc_string, target_opset, targeted_onnx,
---> 30                    channel_first_inputs, custom_conversion_functions, custom_shape_calculators)
     31 
     32 

/usr/local/lib/python3.6/dist-packages/onnxmltools/convert/keras/convert.py in convert(model, name, default_batch_size, initial_types, doc_string, target_opset, targeted_onnx, channel_first_inputs, custom_conversion_functions, custom_shape_calculators)
     46         name = str(uuid4().hex)
     47 
---> 48     onnx_model = convert_topology(topology, name, doc_string, target_opset, targeted_onnx, channel_first_inputs)
     49     return onnx_model

/usr/local/lib/python3.6/dist-packages/onnxmltools/convert/common/_topology.py in convert_topology(topology, model_name, doc_string, target_opset, targeted_onnx, channel_first_inputs)
    719         else:
    720             # Convert the selected operator into some ONNX objects and save them into the container
--> 721             _registration.get_converter(operator.type)(scope, operator, container)
    722 
    723     # When calling ModelComponentContainer's add_initializer(...), nothing is added into the input list. However, in

/usr/local/lib/python3.6/dist-packages/onnxmltools/convert/keras/operator_converters/Conv.py in convert_keras_conv2d(scope, operator, container)
    144 def convert_keras_conv2d(scope, operator, container):
    145     is_transpose, n_dims, input_perm, output_perm, weight_perm = get_converter_config(2, False)
--> 146     convert_keras_conv_core(scope, operator, container, is_transpose, n_dims, input_perm, output_perm, weight_perm)
    147 
    148 

/usr/local/lib/python3.6/dist-packages/onnxmltools/convert/keras/operator_converters/Conv.py in convert_keras_conv_core(scope, operator, container, is_transpose, n_dims, input_perm_axes, output_perm_axes, weight_perm_axes)
    117     # The construction of convolution is done. Now, we create an activation operator to apply the activation specified
    118     # in this Keras layer.
--> 119     apply_activation_function = _activation_map[op.activation]
    120     activation_output_name = scope.get_unique_variable_name('activation_output')
    121     apply_activation_function(scope, intermediate_output_name, activation_output_name, container)

KeyError: <function elu at 0x7fa59f554158>
```

**Comment by faruknane** [comment]
@wenbingl I did it yay. Tried to directly install from github not pypi. So it didn't give any error. Thank you so much. I get happy now. 
```
!pip install onnx==1.3.0
!pip install git+https://github.com/onnx/onnxmltools
```

**Comment by faruknane** [comment]
```
!pip install onnx==1.3.0
!pip install git+https://github.com/onnx/onnxmltools
```

I had to use the converter again. It was working 20 days ago. However, it gives the error of keras2onnx is not installed. When I install that, it gives the same error as before it did (function elu).

**Comment by wenbingl** [comment]
@jiafatom , Can you help with porting the change to keras2onnx?

**Comment by jiafatom** [comment]
@faruknane , can you try directly install keras-onnx from GitHub not pypi? it will install keras2onnx. 

The reason is that we support elu in keras2onnx 3 days ago, see [PR](https://github.com/onnx/keras-onnx/commit/da7ea5a168b2478adb9ff81b1ca31de09795eeee). This is after the package is published to pypi.

**Comment by faruknane** [comment]
@jiafatom Yeah that fixed the problem. Thank you again.
