### ISSUE TITLE
convert_keras KeyError

### ISSUE THREAD

**Issue by lazarkrstic** [onnx/onnxmltools#243]
Hi I use Keras library and I'm trying to create onnx model.

    from keras.models import load_model
    model = load_model("model.h5")
  
    import onnx
    import onnxmltools
    onnx_model = onnxmltools.convert_keras(model, target_opset=7) 

and than I get this error
````
Traceback (most recent call last):

  File "<ipython-input-6-e0251e8abf57>", line 3, in <module>
    onnx_model = onnxmltools.convert_keras(model, target_opset=7)

  File "C:\Users\krstic\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\onnxmltools\convert\main.py", line 30, in convert_keras
    channel_first_inputs, custom_conversion_functions, custom_shape_calculators)

  File "C:\Users\krstic\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\onnxmltools\convert\keras\convert.py", line 48, in convert
    onnx_model = convert_topology(topology, name, doc_string, target_opset, targeted_onnx, channel_first_inputs)

  File "C:\Users\krstic\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\onnxmltools\convert\common\_topology.py", line 721, in convert_topology
    _registration.get_converter(operator.type)(scope, operator, container)

  File "C:\Users\krstic\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\onnxmltools\convert\keras\operator_converters\Dense.py", line 44, in convert_keras_dense
    apply_activation_function = _activation_map[operator.raw_operator.activation]

KeyError: <function tanh at 0x000001882A0390D0>
````

**Comment by lazarkrstic** [comment]
Allowed activation functions are:

* sigmoid
* softmax
* linear
* relu

but my model use `tanh`
