### ISSUE TITLE
Cannot convert tf.keras model to onnx

### ISSUE THREAD

**Issue by gismo07** [onnx/onnxmltools#253]
Hello,

I encountered the problem, that a tensorflow.keras model cannot be converted to onnx using `onnxmltools.convert_keras(myTFKerasModel,target_opset=7)`.  Is this a known issue? How can I convert my trained tf.keras model to onnx? Due to the fact, that I use tfrecords for train and validation, I have to stick to tf.keras instead of plain keras.

### The error message:
```
FailedPreconditionError                   Traceback (most recent call last)
~/miniconda3/envs/onnx-tools/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

~/miniconda3/envs/onnx-tools/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

~/miniconda3/envs/onnx-tools/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

FailedPreconditionError: Error while reading resource variable conv2d_1_2/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/conv2d_1_2/bias)
	 [[{{node conv2d_1_2/bias/Read/ReadVariableOp}} = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv2d_1_2/bias)]]
	 [[{{node dense_3/bias/Read/ReadVariableOp/_29}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_38_dense_3/bias/Read/ReadVariableOp", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

### Test
For testing I used the simple [keras mnist cnn example](https://github.com/keras-team/keras/blob/master/examples/mnist_cnn.py), but changed 
```
import keras as keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
from keras.losses import categorical_crossentropy
from keras.optimizers import Adadelta
```
to
```
import tensorflow.keras as keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras import backend as K
from tensorflow.keras.losses import categorical_crossentropy
from tensorflow.keras.optimizers import Adadelta
```

Without the changes, the trained model can be converted to onnx without any troubles.

#### The full example:
```
import tensorflow.keras as keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras import backend as K
from tensorflow.keras.losses import categorical_crossentropy
from tensorflow.keras.optimizers import Adadelta

import onnxmltools
from tensorflow.keras.models import load_model
import numpy as np
import onnx


batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)


model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))


model.compile(loss=categorical_crossentropy,
              optimizer=Adadelta(),
              metrics=['accuracy'])


model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])


model.save('./myTFKerasModel.h5')


kearsModel = load_model('./myTFKerasModel.h5')
onnxModel = onnxmltools.convert_keras(kearsModel,target_opset=7)

```

Thank you, for your help

**Comment by wenbingl** [comment]
we only supports the model generated by the standalone keras package.
But there is a tensorflow converter so you save your tf.keras model as a frozen graph and try to convert this graph to onnx model.

**Comment by dsacdalan** [comment]
What happens when you attempt to convert the model without training?

I'm currently having an issue converting a Keras model into ONNX. If I convert _before_ I train, it converts the model just fine. If I load the model with just the weights from a .hdf5 or the entire model from a .h5, it fails.

I also get a FailedPreconditionError, and it is on the bias of my softmax output.

**Comment by JiguangShen** [comment]
I did in this way and it worked:
1.  Create a mirror model in Keras.
2.  Load the weights from tf.keras to Keras.
3.  Convert from pure Keras model.

**Comment by wenbingl** [comment]
The latest keras2onnx supports tf.keras now, Can you have a try again?

**Comment by MarionVltt** [comment]
Hi, 
I encountered the same problem with tf.keras today, I have a CNN model, and I get a similar error (see below). I tried saving it before and after training but the error is still there, but about a different layer. 

Here is the model (all tensorflow.keras layers)
```
model = Sequential()
model.add(Embedding(input_dim=vocab_size,output_dim=300,input_length=max_len, weights=[wv_matrix], trainable=False))
#model.add(Dropout(rate=0.2)) #dropout rate
model.add(Conv1D(filters=32, kernel_size=3, activation='relu', bias_initializer='random_uniform', padding='same'))
model.add(MaxPooling1D(pool_size=3))
model.add(Conv1D(filters=32*2, kernel_size=3, activation='relu', bias_initializer='random_uniform', padding='same'))
model.add(GlobalMaxPool1D())
#model.add(Dropout(rate=0.2))
model.add(Dense(1, activation='sigmoid'))
optimizer = tf.keras.optimizers.Adam(lr=0.001)
model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['acc'])
onnx_model = keras2onnx.convert_keras(model, "Binary_model_final")
model_serialized = onnx_model.SerializeToString()
```
I also tried using onnxtools.convert_keras on the .h5 file (like here : https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/keras_onnx.ipynb), but I got the sameerror.

Here the log of the error if I try to save it before training: 
```
FailedPreconditionError: Error while reading resource variable embedding_1/embeddings from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/embedding_1/embeddings/N10tensorflow3VarE does not exist.
	 [[node embedding_1/embeddings/Read/ReadVariableOp (defined at <ipython-input-23-446ac9fc3c87>:2) ]]
	 [[node embedding_1/embeddings/Read/ReadVariableOp (defined at <ipython-input-23-446ac9fc3c87>:2) ]]

Caused by op 'embedding_1/embeddings/Read/ReadVariableOp', defined at:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1451, in _run_once
    handle._run()
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 781, in inner
    self.run()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3049, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3214, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-446ac9fc3c87>", line 2, in <module>
    model.add(Embedding(input_dim=vocab_size,output_dim=300,input_length=max_len, weights=[wv_matrix], trainable=False))
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 442, in _method_wrapper
    method(self, *args, **kwargs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/engine/sequential.py", line 164, in add
    layer(x)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 151, in wrapper
    output_shape = fn(instance, input_shape)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/layers/embeddings.py", line 142, in build
    constraint=self.embeddings_constraint)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 349, in add_weight
    aggregation=aggregation)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 607, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 145, in make_variable
    aggregation=aggregation)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 213, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 176, in _variable_v1_call
    aggregation=aggregation)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 155, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2488, in default_variable_creator
    import_scope=import_scope)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 217, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 294, in __init__
    constraint=constraint)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 446, in _init_from_args
    value = self._read_variable_op()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 728, in _read_variable_op
    self._dtype)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 550, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Error while reading resource variable embedding_1/embeddings from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/embedding_1/embeddings/N10tensorflow3VarE does not exist.
	 [[node embedding_1/embeddings/Read/ReadVariableOp (defined at <ipython-input-23-446ac9fc3c87>:2) ]]
	 [[node embedding_1/embeddings/Read/ReadVariableOp (defined at <ipython-input-23-446ac9fc3c87>:2) ]]
```

and here is the log when trying to save after training:
```
FailedPreconditionError: Error while reading resource variable dense/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/dense/kernel)
	 [[node dense/kernel/Read/ReadVariableOp (defined at <ipython-input-17-446ac9fc3c87>:9) ]]

Caused by op 'dense/kernel/Read/ReadVariableOp', defined at:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1451, in _run_once
    handle._run()
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 781, in inner
    self.run()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 378, in dispatch_queue
    yield self.process_one()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 225, in wrapper
    runner = Runner(result, future, yielded)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 708, in __init__
    self.run()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3049, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3214, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-446ac9fc3c87>", line 9, in <module>
    model.add(Dense(1, activation='sigmoid'))
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 442, in _method_wrapper
    method(self, *args, **kwargs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/engine/sequential.py", line 180, in add
    output_tensor = layer(self.outputs[0])
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 949, in build
    trainable=True)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 349, in add_weight
    aggregation=aggregation)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 607, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 145, in make_variable
    aggregation=aggregation)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 213, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 176, in _variable_v1_call
    aggregation=aggregation)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 155, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2488, in default_variable_creator
    import_scope=import_scope)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 217, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 294, in __init__
    constraint=constraint)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 446, in _init_from_args
    value = self._read_variable_op()
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 728, in _read_variable_op
    self._dtype)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 550, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/supercalculateur/environment/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Error while reading resource variable dense/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/dense/kernel)
	 [[node dense/kernel/Read/ReadVariableOp (defined at <ipython-input-17-446ac9fc3c87>:9) ]]
```

Do you have any ideas about the problem? Thank you

**Comment by vinitra** [comment]
@MarionVltt, sorry for missing your earlier comments! I'm moving this issue to the keras2onnx repository.
