### ISSUE TITLE
Convert Keras to ONNX Err on Mac

### ISSUE THREAD

**Issue by TaylorHere** [onnx/onnxmltools#328]
```
❯ python3 test.py
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0812 19:11:07.967262 4745819584 deprecation_wrapper.py:119] From /usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0812 19:11:08.001241 4745819584 deprecation_wrapper.py:119] From /usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0812 19:11:08.006119 4745819584 deprecation_wrapper.py:119] From /usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

test.py:24: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=[<tf.Tenso..., outputs=Tensor("ad...)`
  keras_model = Model(inputs=[input1, input2], output=sub_sum)
W0812 19:11:08.181174 4745819584 deprecation_wrapper.py:119] From /usr/local/lib/python3.7/site-packages/keras2onnx/common/utils.py:42: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0812 19:11:08.181406 4745819584 deprecation_wrapper.py:119] From /usr/local/lib/python3.7/site-packages/keras2onnx/common/utils.py:42: The name tf.logging.WARN is deprecated. Please use tf.compat.v1.logging.WARN instead.

Traceback (most recent call last):
  File "test.py", line 27, in <module>
    onnx_model = onnxmltools.convert_keras(keras_model, target_opset=7)
  File "/usr/local/lib/python3.7/site-packages/onnxmltools/convert/main.py", line 32, in convert_keras
    return convert(model, name, doc_string, target_opset, channel_first_inputs)
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/main.py", line 103, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/topology.py", line 216, in convert_topology
    container.add_output(tensor_outputs[name])
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/common/interim.py", line 192, in add_output
    self.outputs.append(self._make_value_info(variable))
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/common/interim.py", line 173, in _make_value_info
    value_info.type.CopyFrom(variable.type.to_onnx_type())
  File "/usr/local/lib/python3.7/site-packages/onnxconverter_common/data_types.py", line 87, in to_onnx_type
    raise ValueError('Unsupported dimension type: %s' % type(d))
ValueError: Unsupported dimension type: <class 'NoneType'>

```
when I follow the code in README.md, I got this err output
this is my code looks like
my platform is MacOS

```python3
import onnxmltools
from keras.layers import Input, Dense, Add
from keras.models import Model

# N: batch size, C: sub-model input dimension, D: final model's input dimension
N, C, D = 2, 3, 3

# Define a sub-model, it will become a part of our final model
sub_input1 = Input(shape=(C,))
sub_mapped1 = Dense(D)(sub_input1)
sub_model1 = Model(inputs=sub_input1, outputs=sub_mapped1)

# Define another sub-model, it will become a part of our final model
sub_input2 = Input(shape=(C,))
sub_mapped2 = Dense(D)(sub_input2)
sub_model2 = Model(inputs=sub_input2, outputs=sub_mapped2)

# Define a model built upon the previous two sub-models
input1 = Input(shape=(D,))
input2 = Input(shape=(D,))
mapped1_2 = sub_model1(input1)
mapped2_2 = sub_model2(input2)
sub_sum = Add()([mapped1_2, mapped2_2])
keras_model = Model(inputs=[input1, input2], output=sub_sum)

# Convert it! The target_opset parameter is optional.
onnx_model = onnxmltools.convert_keras(keras_model, target_opset=7) 
```

**Comment by TaylorHere** [comment]
I install onnxruntime and onnxmltools by pip3
version is :
```
onnx                          1.5.0
onnxconverter-common          1.5.0
onnxmltools                   1.5.0
onnxruntime                   0.5.0
```

**Comment by TaylorHere** [comment]
It's working on Linux
