### ISSUE TITLE
 Unsupported shape calculation for operator visionFeaturePrint - Converting CoreML to ONNX

### ISSUE THREAD

**Issue by MarcusSjolin** [onnx/onnxmltools#354]
Seems to be unsupported

```
Traceback (most recent call last):
  File "convert.py", line 9, in <module>
    onnx_model = onnxmltools.convert_coreml(coreml_model, 'Example Model')
  File "/Library/Python/3.7/site-packages/onnxmltools/convert/main.py", line 18, in convert_coreml
    custom_conversion_functions, custom_shape_calculators)
  File "/Library/Python/3.7/site-packages/onnxmltools/convert/coreml/convert.py", line 60, in convert
    topology = parse_coreml(spec, initial_types, target_opset, custom_conversion_functions, custom_shape_calculators)
  File "/Library/Python/3.7/site-packages/onnxmltools/convert/coreml/_parse.py", line 467, in parse_coreml
    topology.compile()
  File "/Library/Python/3.7/site-packages/onnxconverter_common/topology.py", line 632, in compile
    self._infer_all_types()
  File "/Library/Python/3.7/site-packages/onnxconverter_common/topology.py", line 508, in _infer_all_types
    operator.infer_types()
  File "/Library/Python/3.7/site-packages/onnxconverter_common/topology.py", line 110, in infer_types
    registration.get_shape_calculator(self.type)(self)
  File "/Library/Python/3.7/site-packages/onnxconverter_common/registration.py", line 68, in get_shape_calculator
    raise ValueError('Unsupported shape calculation for operator %s' % operator_name)
ValueError: Unsupported shape calculation for operator visionFeaturePrint
```

**Comment by me-Stoffel** [comment]
Ran into the same issue, just trying to convert a very simple image classification model. Is this not yet supported in general for CoreML to ONNX?

**Comment by poolplayer32285** [comment]
Im running into this issue still also.

**Comment by jbrown15** [comment]
I too, am running into this issue.

**Comment by codabrink** [comment]
Just ran into this issue today as well.

**Comment by rextremotabaresDtt** [comment]
Hi guys, any update on this? Are these models not suported? If so, how can you export coreml to another format?

**Comment by thomassantosh** [comment]
Same here, just got the same error converting a basic image classification into ONNX, using ```onnxmltools```.

**Comment by brown2021** [comment]
I have been having this issue for over a year now lol. I am looking for a
clean way to convert a coreml model to a pytorch

**Comment by fuomag9** [comment]
Still not working in 6.0 :(

**Comment by abhishekwynum** [comment]
Did this receive any fix on the current version ?

**Comment by brown2021** [comment]
To my understanding it will never be fixed. I think Apple intentionally
stopped supporting their model to be converted. But it has supported the
other direction, converting from other libraries to coreML.

**Comment by StainlessStlRat** [comment]
To my eyes it looks like we have full access to the model via coremltools so it shouldn't be impossible to write a shape calculator.
