### ISSUE TITLE
cannot import name 'onnx' from 'onnxmltools.proto' 

### ISSUE THREAD

**Issue by T43113452** [onnx/onnxmltools#439]
WARNING:root:scikit-learn version 0.24.0 is not supported. Minimum required version: 0.17. Maximum required version: 0.19.2. Disabling scikit-learn conversion API.
Traceback (most recent call last):
  File "convert_to_onnx.py", line 2, in <module>
    from winmltools import convert_coreml
  File "/home/zhengchuquan/.conda/envs/tf2onnx/lib/python3.7/site-packages/winmltools/__init__.py", line 20, in <module>
    from .convert import convert_coreml
  File "/home/zhengchuquan/.conda/envs/tf2onnx/lib/python3.7/site-packages/winmltools/convert/__init__.py", line 7, in <module>
    from .main import convert_coreml
  File "/home/zhengchuquan/.conda/envs/tf2onnx/lib/python3.7/site-packages/winmltools/convert/main.py", line 7, in <module>
    from .common import tf2onnx_installed, utils
  File "/home/zhengchuquan/.conda/envs/tf2onnx/lib/python3.7/site-packages/winmltools/convert/common/__init__.py", line 9, in <module>
    from .ModelBuilder import ModelBuilder
  File "/home/zhengchuquan/.conda/envs/tf2onnx/lib/python3.7/site-packages/winmltools/convert/common/ModelBuilder.py", line 9, in <module>
    from . import model_util
  File "/home/zhengchuquan/.conda/envs/tf2onnx/lib/python3.7/site-packages/winmltools/convert/common/model_util.py", line 8, in <module>
    from .NodeBuilder import NodeBuilder
  File "/home/zhengchuquan/.conda/envs/tf2onnx/lib/python3.7/site-packages/winmltools/convert/common/NodeBuilder.py", line 8, in <module>
    from ...proto import onnx_proto
  File "/home/zhengchuquan/.conda/envs/tf2onnx/lib/python3.7/site-packages/winmltools/proto/__init__.py", line 8, in <module>
    from onnxmltools.proto import onnx
ImportError: cannot import name 'onnx' from 'onnxmltools.proto' (/home/zhengchuquan/.conda/envs/tf2onnx/lib/python3.7/site-packages/onnxmltools/proto/__init__.py)

**Comment by ryanneilstroud** [comment]
Same issue. Any luck?

**Comment by xadupre** [comment]
A new version of onnxmltools we just released but this impor should still fail. But this is more an issue for winmltools, not onnxmltools.
