### ISSUE TITLE
Cannot convert pyspark KMeans to ONNX

### ISSUE THREAD

**Issue by alvaro-budria** [onnx/onnxmltools#538]
When trying to export a pyspark KMeans fitted model to ONNX, I run into an error saying that there is no operator for the object I'm  passing in. Moreover, it seems there are currently no tests for pyspark KMeans [here](https://github.com/onnx/onnxmltools/tree/main/tests/sparkml). Does that indicate that KMeans conversion is not supported yet?

Here is a minimum working example of what I'm trying to accomplish:

```
from pyspark.ml.clustering import KMeans
from pyspark.ml.linalg import Vectors
from pyspark.sql import SparkSession

from onnxconverter_common.data_types import FloatTensorType
from onnxmltools.convert import convert_sparkml

from onnx.defs import onnx_opset_version
from onnxconverter_common.onnx_ex import DEFAULT_OPSET_NUMBER
TARGET_OPSET = min(DEFAULT_OPSET_NUMBER, onnx_opset_version())


spark = SparkSession.builder.master("local") \
                    .appName("onnxConversion") \
                    .getOrCreate()

data = [(Vectors.dense([0.0, 0.0]),), (Vectors.dense([1.0, 1.0]),),
        (Vectors.dense([9.0, 8.0]),), (Vectors.dense([8.0, 9.0]),)]
df = spark.createDataFrame(data, ["features"])
kmeans = KMeans(k=2, seed=1)
model = kmeans.fit(df)
initial_types = [('features', FloatTensorType([None, 2]))]
convert_sparkml(model, 'kmeans', initial_types, spark_session=spark, target_opset=TARGET_OPSET)
```

The complete error message:

> 22/04/01 12:48:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
22/04/01 12:49:10 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
22/04/01 12:49:10 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS
Traceback (most recent call last):                                              
  File "kmeansIssue.py", line 23, in <module>
    convert_sparkml(model, 'kmeans', initial_types, spark_session=spark, target_opset=TARGET_OPSET)
  File "/Users/alvarobudria/anaconda3/envs/py37/lib/python3.7/site-packages/onnxmltools/convert/main.py", line 167, in convert_sparkml
    custom_conversion_functions, custom_shape_calculators, spark_session)
  File "/Users/alvarobudria/anaconda3/envs/py37/lib/python3.7/site-packages/onnxmltools/convert/sparkml/convert.py", line 65, in convert
    topology = parse_sparkml(spark_session, model, initial_types, target_opset, custom_conversion_functions, custom_shape_calculators)
  File "/Users/alvarobudria/anaconda3/envs/py37/lib/python3.7/site-packages/onnxmltools/convert/sparkml/_parse.py", line 119, in parse_sparkml
    _parse_sparkml(spark, scope, model, inputs, output_dict)
  File "/Users/alvarobudria/anaconda3/envs/py37/lib/python3.7/site-packages/onnxmltools/convert/sparkml/_parse.py", line 87, in _parse_sparkml
    return _parse_sparkml_simple_model(spark, scope, model, global_inputs, output_dict)
  File "/Users/alvarobudria/anaconda3/envs/py37/lib/python3.7/site-packages/onnxmltools/convert/sparkml/_parse.py", line 48, in _parse_sparkml_simple_model
    this_operator = scope.declare_local_operator(get_sparkml_operator_name(type(model)), model)
  File "/Users/alvarobudria/anaconda3/envs/py37/lib/python3.7/site-packages/onnxmltools/convert/sparkml/ops_names.py", line 87, in get_sparkml_operator_name
    raise ValueError("No proper operator name found for '%s'" % model_type)
ValueError: No proper operator name found for '<class 'pyspark.ml.clustering.KMeansModel'>'

**Comment by memoryz** [comment]
It's supported now.

**Comment by memoryz** [comment]
@xadupre please close this issue.
