### ISSUE TITLE
Error converting from mlmodel to onnx: Unsupported shape calculation for operator expandDims

### ISSUE THREAD

**Issue by rmajasol** [onnx/onnxmltools#541]
Got error when trying to convert my .mlmodel to onnx model following onnxmltools documentation: https://github.com/onnx/onnxmltools#coreml-to-onnx-conversion

```python
import onnxmltools
import coremltools

# Load a Core ML model
coreml_model = coremltools.utils.load_spec('hands.mlmodel')

# Convert the Core ML model into ONNX
onnx_model = onnxmltools.convert_coreml(coreml_model, 'Hands Pose Model')

# Save as protobuf
onnxmltools.utils.save_model(onnx_model, 'hands.onnx')
```

Here in this line exactly:
```python
onnx_model = onnxmltools.convert_coreml(coreml_model, 'Hands Pose Model')
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rmaja/opt/miniconda3/envs/coreml/lib/python3.6/site-packages/onnxmltools/convert/main.py", line 18, in convert_coreml
    custom_conversion_functions, custom_shape_calculators)
  File "/Users/rmaja/opt/miniconda3/envs/coreml/lib/python3.6/site-packages/onnxmltools/convert/coreml/convert.py", line 57, in convert
    topology = parse_coreml(spec, initial_types, target_opset, custom_conversion_functions, custom_shape_calculators)
  File "/Users/rmaja/opt/miniconda3/envs/coreml/lib/python3.6/site-packages/onnxmltools/convert/coreml/_parse.py", line 463, in parse_coreml
    topology.compile()
  File "/Users/rmaja/opt/miniconda3/envs/coreml/lib/python3.6/site-packages/onnxconverter_common/topology.py", line 678, in compile
    self._infer_all_types()
  File "/Users/rmaja/opt/miniconda3/envs/coreml/lib/python3.6/site-packages/onnxconverter_common/topology.py", line 553, in _infer_all_types
    operator.infer_types()
  File "/Users/rmaja/opt/miniconda3/envs/coreml/lib/python3.6/site-packages/onnxconverter_common/topology.py", line 107, in infer_types
    get_shape_calculator(self.type)(self)
  File "/Users/rmaja/opt/miniconda3/envs/coreml/lib/python3.6/site-packages/onnxconverter_common/registration.py", line 67, in get_shape_calculator
    raise ValueError('Unsupported shape calculation for operator %s' % operator_name)
ValueError: Unsupported shape calculation for operator expandDims
```

Environment:
- macOS 12.3.1
- python 3.8
- coremltools==5.2.0 (latest version)
- onnxmltools==1.11.0 (latest version)

Here all python packages installed:
```
certifi==2021.5.30
coremltools==5.2.0
importlib-resources==5.4.0
joblib==1.1.0
mpmath==1.2.1
numpy==1.19.5
onnx==1.11.0
onnxconverter-common==1.9.0
onnxmltools==1.11.0
packaging==21.3
protobuf==3.17.2
pyparsing==3.0.8
scikit-learn==0.24.2
scipy==1.5.4
six @ file:///tmp/build/80754af9/six_1644875935023/work
skl2onnx==1.11.1
sympy==1.9
threadpoolctl==3.1.0
tqdm==4.64.0
typing_extensions==4.1.1
zipp==3.6.0
```

Maybe expandDims is not supported yet for coremltools 5.2.0 despite being the latest version?

Thanks,

**Comment by AlejoPrietoDavalos** [comment]
I have the same error
