### ISSUE TITLE
AttributeError: 'Booster' object has no attribute 'attr'

### ISSUE THREAD

**Issue by rvoak** [onnx/onnxmltools#636]
I'm training a LightGBM model and converting it to the ONNX format. But I encounter the following error message:
`AttributeError: 'Booster' object has no attribute 'attr'`. 

Here's my code snippet:
```
import lightgbm as lgb
import onnx
import onnxmltools
from onnxconverter_common.data_types import FloatType, StringType

train_data = lgb.Dataset(X,
                             label = Y,
                             categorical_feature = [287,288])
                             
# Train LightGBM Model
params = {
                'objective': 'binary',
                'metric': 'binary_logloss',
                'boosting_type': 'gbdt'
                }
model = lgb.train(params, train_data)
    

# The first few features are Float, the last two are categorical
init_types = [('continuous_feature', FloatType([None, 286])),('categorical_feature', StringType([None, 2]))]

onnx_model = onnxmltools.convert_lightgbm(model, initial_types = init_types)
```

Here's the full traceback:
```
Traceback (most recent call last):
  File "resources/TrainMLModel.py", line 60, in <module>
    train()
  File "resources/TrainMLModel.py", line 53, in train
    onnx_model = onnxmltools.convert_lightgbm(model, initial_types = init_types)
  File "/usr/local/lib/python3.6/site-packages/onnxmltools/convert/main.py", line 139, in convert_lightgbm
    zipmap=zipmap, split=split)
  File "/usr/local/lib/python3.6/site-packages/onnxmltools/convert/lightgbm/convert.py", line 59, in convert
    model = WrappedBooster(model)
  File "/usr/local/lib/python3.6/site-packages/onnxmltools/convert/lightgbm/_parse.py", line 25, in __init__
    self.objective_ = self.get_objective()
  File "/usr/local/lib/python3.6/site-packages/onnxmltools/convert/lightgbm/_parse.py", line 62, in get_objective
    objective = self.booster_.attr('objective')
AttributeError: 'Booster' object has no attribute 'attr'
```

**Comment by xadupre** [comment]
This should disappear with PR #634.

**Comment by xadupre** [comment]
I'll close this issue. Feel free to reopen it if needed.
