### ISSUE TITLE
Python 3.9 CoreML conversion

### ISSUE THREAD

**Issue by b005t3r** [onnx/onnxmltools#687]
I've been trying to make it work with CoreML models and Python 3.9, but I don't see how.

It does't work with the most recent version of CoreML tools, the required version (3.1) does only work with Python 2.7, but with 2.7 I wasn't able to install onnxmltools...

Is there a way to make it work that I'm somehow missing?

**Comment by b005t3r** [comment]
This is what I'm getting when running your example script:

```
Traceback (most recent call last):
  File "/Users/booster/Documents/Python/ONNXConverter/main.py", line 8, in <module>
    onnx_model = onnxmltools.convert_coreml(coreml_model, 'Example Model')
  File "/Users/booster/Documents/Python/ONNXConverter/venviro/lib/python3.9/site-packages/onnxmltools/convert/main.py", line 30, in convert_coreml
    return convert(
  File "/Users/booster/Documents/Python/ONNXConverter/venviro/lib/python3.9/site-packages/onnxmltools/convert/coreml/convert.py", line 70, in convert
    topology = parse_coreml(
  File "/Users/booster/Documents/Python/ONNXConverter/venviro/lib/python3.9/site-packages/onnxmltools/convert/coreml/_parse.py", line 658, in parse_coreml
    _parse_model(topology, scope, model)
  File "/Users/booster/Documents/Python/ONNXConverter/venviro/lib/python3.9/site-packages/onnxmltools/convert/coreml/_parse.py", line 163, in _parse_model
    _parse_pipeline_model(topology, scope, model, inputs, outputs)
  File "/Users/booster/Documents/Python/ONNXConverter/venviro/lib/python3.9/site-packages/onnxmltools/convert/coreml/_parse.py", line 315, in _parse_pipeline_model
    _parse_model(topology, scope, sub_model, sub_inputs, sub_outputs)
  File "/Users/booster/Documents/Python/ONNXConverter/venviro/lib/python3.9/site-packages/onnxmltools/convert/coreml/_parse.py", line 169, in _parse_model
    _parse_neural_network_model(topology, scope, model, inputs, outputs)
  File "/Users/booster/Documents/Python/ONNXConverter/venviro/lib/python3.9/site-packages/onnxmltools/convert/coreml/_parse.py", line 489, in _parse_neural_network_model
    operator_type = find_type_conversion(
  File "/Users/booster/Documents/Python/ONNXConverter/venviro/lib/python3.9/site-packages/onnxconverter_common/data_types.py", line 251, in find_type_conversion
    if isinstance(source_type, target_type):
TypeError: isinstance() arg 2 must be a type or tuple of types
```

The script:
```python
import onnxmltools
import coremltools

# Load a Core ML model
coreml_model = coremltools.utils.load_spec('input.mlmodel')

# Convert the Core ML model into ONNX
onnx_model = onnxmltools.convert_coreml(coreml_model, 'Example Model')

# Save as protobuf
onnxmltools.utils.save_model(onnx_model, 'output.onnx')
```

**Comment by b005t3r** [comment]
Also tried the same thing with Python 3.7 which does work with coremltools 3.7 and onnxmltools, but I'm getting this error:

```
Traceback (most recent call last):
  File "/Users/booster/Documents/Python/ONNXConverter/main.py", line 8, in <module>
    onnx_model = onnxmltools.convert_coreml(coreml_model, 'Example Model')
  File "/opt/anaconda3/envs/ONNXConverter/lib/python3.7/site-packages/onnxmltools/convert/main.py", line 38, in convert_coreml
    custom_shape_calculators,
  File "/opt/anaconda3/envs/ONNXConverter/lib/python3.7/site-packages/onnxmltools/convert/coreml/convert.py", line 75, in convert
    custom_shape_calculators,
  File "/opt/anaconda3/envs/ONNXConverter/lib/python3.7/site-packages/onnxmltools/convert/coreml/_parse.py", line 659, in parse_coreml
    topology.compile()
  File "/opt/anaconda3/envs/ONNXConverter/lib/python3.7/site-packages/onnxconverter_common/topology.py", line 678, in compile
    self._infer_all_types()
  File "/opt/anaconda3/envs/ONNXConverter/lib/python3.7/site-packages/onnxconverter_common/topology.py", line 553, in _infer_all_types
    operator.infer_types()
  File "/opt/anaconda3/envs/ONNXConverter/lib/python3.7/site-packages/onnxconverter_common/topology.py", line 107, in infer_types
    get_shape_calculator(self.type)(self)
  File "/opt/anaconda3/envs/ONNXConverter/lib/python3.7/site-packages/onnxconverter_common/registration.py", line 67, in get_shape_calculator
    raise ValueError('Unsupported shape calculation for operator %s' % operator_name)
ValueError: Unsupported shape calculation for operator scalerPreprocessor
```

**Comment by ConnorLynchLV8** [comment]
I am also experiencing this issue. Same code

**Comment by alinzh** [comment]
I can't find a solution too. Everywhere this question is open and not resolved ;(

**Comment by b005t3r** [comment]
Yeah, I don't think this is supported anymore.

**Comment by xadupre** [comment]
Cloding the issue. Feel free to reopen.

**Comment by KamalrajTV** [comment]
Is there any other way to convert the Core ML model to onnx?
