### ISSUE TITLE
Fail to import BlobReader from libmilstoragepython. No module named 'coremltools.libmilstoragepython'

### ISSUE THREAD

**Issue by longge-vision** [onnx/onnxmltools#693]
D:\yolov10\yolov10-main>CALL d:\Anaconda3\Scripts\activate.bat d:\Anaconda3\envs\yolov10
2024-05-31 18:03:03.393293: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-31 18:03:04.232945: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
TensorFlow version 2.16.1 has not been tested with coremltools. You may run into unexpected errors. TensorFlow 2.12.0 is the most recent version that has been tested.
Failed to load _MLModelProxy: No module named 'coremltools.libcoremlpython'
Fail to import BlobReader from libmilstoragepython. No module named 'coremltools.libmilstoragepython'
Fail to import BlobWriter from libmilstoragepython. No module named 'coremltools.libmilstoragepython'
Traceback (most recent call last):
  File "D:\yolov10\yolov10-main\coreml2onnx.py", line 8, in <module>
    onnx_model = onnxmltools.convert_coreml(coreml_model, 'Example Model')
  File "d:\Anaconda3\envs\yolov10\lib\site-packages\onnxmltools\convert\main.py", line 30, in convert_coreml
    return convert(
  File "d:\Anaconda3\envs\yolov10\lib\site-packages\onnxmltools\convert\coreml\convert.py", line 70, in convert
    topology = parse_coreml(
  File "d:\Anaconda3\envs\yolov10\lib\site-packages\onnxmltools\convert\coreml\_parse.py", line 659, in parse_coreml
    topology.compile()
  File "d:\Anaconda3\envs\yolov10\lib\site-packages\onnxconverter_common\topology.py", line 678, in compile
    self._infer_all_types()
  File "d:\Anaconda3\envs\yolov10\lib\site-packages\onnxconverter_common\topology.py", line 553, in _infer_all_types
    operator.infer_types()
  File "d:\Anaconda3\envs\yolov10\lib\site-packages\onnxconverter_common\topology.py", line 107, in infer_types
    get_shape_calculator(self.type)(self)
  File "d:\Anaconda3\envs\yolov10\lib\site-packages\onnxconverter_common\registration.py", line 67, in get_shape_calculator

**Comment by xadupre** [comment]
The converters for coremltools are not actively maintened. The unit test are not run anymore. Is there any way to convert the original model from pytorch or tensorflow to onnx instead?
